CREATE TABLE IF NOT EXISTS handicaps(
   id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT
  ,Course VARCHAR(30)  NOT NULL
  ,Par INTEGER NOT NULL
  ,Rating FLOAT NOT NULL
  ,Slope FLOAT  NOT NULL
  ,Score INTEGER  NOT NULL
  ,Handicap FLOAT  NOT NULL
);